# Generated by Django 5.0.1 on 2024-01-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
