# Generated by Django 5.0.1 on 2024-01-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='fruit',
        ),
        migrations.AddField(
            model_name='userdata',
            name='fruit_selection',
            field=models.CharField(choices=[('apple', 'Apple'), ('banana', 'Banana'), ('orange', 'Orange'), ('grapes', 'Grape'), ('pineapple', 'Pineapple'), ('watermelon', 'Watermelon'), ('lychee', 'Lychee'), ('mango', 'Mango')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
